# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  pull_request:

jobs:
  maven-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      - name: Search for bad unicode translations
        run: |
          find . -name \*.properties -exec grep '\\u[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][^0-9a-fA-F]' {} \; &> grep.txt
          find . -name \*.properties -exec grep '\\u[0-9a-fA-F][0-9a-fA-F][^0-9a-fA-F][0-9a-fA-F]' {} \; &>> grep.txt
          find . -name \*.properties -exec grep '\\u[0-9a-fA-F][^0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]' {} \; &>> grep.txt
          find . -name \*.properties -exec grep '\\u[^0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]' {} \; &>> grep.txt
          if [ -s grep.txt ]; then
            exit 1
          fi
      - name: Run tests with US locale
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.wagon.http.retryHandler.count=2 -Dmaven.wagon.http.pool=true
        run: mvn -V -B -ntp -PskipBrokenTests test
      - name: Run tests with ES locale
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.wagon.http.retryHandler.count=2 -Dmaven.wagon.http.pool=true
        run: mvn -Duser.language=es -Duser.country=ES -V -B -ntp -PskipBrokenTests test
